version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://spring-app:8080"
      - "--domain=alive-hardly-flamingo.ngrok-free.app"
    environment:
      NGROK_AUTHTOKEN: "2uVoxr4hwv8UFtnRedsVnJrxCok_7Ace8kwPTrH3bCNsjksGq"
    ports:
      - "4040:4040"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge